[project]
name = "paper-translator"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "Heegreis", email = "run3113214@gmail.com"}]
requires-python = ">= 3.11"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.ruff.lint]
select = ["I"]

[tool.ruff.format]
quote-style = "single"
